[project]
name = "neuron"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.12.6"
dependencies = [
    "be-great>=0.0.8",
    "flaml>=2.3.2",
    "groq>=0.11.0",
    "openai>=1.54.3",
    "pandas>=2.2.3",
    "termcolor>=2.5.0",
    "torch>=2.5.1",
    "transformers>=4.46.2",
]

[tool.uv]
dev-dependencies = [
    "ipykernel>=6.29.5",
    "pytest-cov>=6.0.0",
    "pytest>=8.3.3",
]
